[package]
name = "dirt"
version = "0.0.0"
description = "Summarize disk usage of the set of files, recursively for directories"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
edition = "2018"

[lib]
name = "dirt"
path = "src/lib.rs"

[[bin]]
name = "dirt"
path = "src/main.rs"

[dependencies]
pipe-trait = "^0.3.2"
structopt = "^0.3.21"
structopt-utilities = "^0.0.8"
smart-default = "^0.6.0"
derive_more = "^0.99.13"
rayon = "^1.5.0"
text-block-macros = "^0.1.0"

[dev-dependencies]
build-fs-tree = "^0.2.5"
maplit = "^1.0.2"
pretty_assertions = "^0.7.2"
rand = "^0.8.3"
